name: ctd
services:
  api:
    image: ctd/api
    pull_policy: build
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "2001:8080"
  web:
    image: ctd/web
    pull_policy: build
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "2000:80"
    depends_on:
      - api